apiVersion: v1
kind: Namespace
metadata:
  name: postgres-dev
  labels:
    name: development

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-conf
  namespace: postgres-dev
  labels:
    name: postgres-dev
data:
  POSTGRES_DB: pgsql-dev
  POSTGRES_USER: pgsql-dev
  POSTGRES_PASSWORD: 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dev
  namespace: postgres-dev
  labels:
    app: postgres-dev
spec:
  selector:
    matchLabels:
      app: postgres-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-dev 
    spec:
      containers:
        - name: postgres-dev
          image: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgres-conf

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-dev
  labels:
    app: postgres-dev
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-dev

